### ISSUE TITLE
Sync milestones and labels

### ISSUE THREAD

**Issue by tamslo** [tamslo/gitlab-issue-automation#10]
If a ticket has a label assigned that is named like a milestone it should be added to this milestone and vice-versa.

* [ ] Get list of labels (group vs. repository)
* [ ] Get list of milestones (group vs. repository)
* Iterate over milestone names
  * [ ] Get all issues with `label == milestone name`; if not in milestone, add to milestone
  * [ ] Get all issues in milestone; if not present, add label
* [ ] Add description to README
