### ISSUE TITLE
[Epic] Improve standup notes

### ISSUE THREAD

**Issue by tamslo** [tamslo/gitlab-issue-automation#20]
- [ ] #7
- [ ] #19
- [ ] It should be possible to trigger standup notes from pipelines (possible to pass "force" variable)?
- [ ] Remove automatically creating standup notes, should always depend on variable
- [ ] Add to ignored labels or define project labels somewhere (maybe connected to #10)
- [ ] Issues should be list without formatting (like bullet points) in format <Issue title> (<issue number with link>)
- [ ] Automatically fill table
