### ISSUE TITLE
Simplify exception definition

### ISSUE THREAD

**Issue by tamslo** [tamslo/gitlab-issue-automation#9]
## Tasks
* [ ] Instead of `start` and `end` one should be able to add a `date` for one-day exceptions
* [ ] Instead of `rules` exceptions should have affiliated issues
* [ ] Add comment that exceptions apply to creation date, not due date (with example)

## Finishing
* [ ] Make sure changes are included in README
* [ ] Make sure to adapt present exceptions
